### ISSUE TITLE
Support POST variant of validators api

### ISSUE THREAD

**Issue by nflaig** [sifraitech/grandine#28]
We are looking into using the POST variant of validators api ([postStateValidators](https://ethereum.github.io/beacon-APIs/#/Beacon/postStateValidators)) but during interop testing I noticed Grandine returns a 405 error. I am guessing you have not yet implemented it.

I wanna make sure Lodestar VC is compatible with Grandine, as a workaround, we can also retry the GET variant of the API if we receive a 405 error.

Let me know if you are planning to implement this soon, can also hold off on merging this on our side.

**Comment by Tumas** [comment]
hey @nflaig, did you have the chance to test this? Fix has been merged to develop.

**Comment by nflaig** [comment]
Confirmed the fix by running the following config:

```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: grandine
    cl_image: ethpandaops/grandine:develop-minimal
    vc_type: lodestar
    vc_image: nflaig/lodestar:post-validators
    vc_extra_params:
      - --http.requestWireFormat=ssz
    count: 4
network_params:
  genesis_delay: 60
  num_validator_keys_per_node: 64
additional_services:
  - assertoor
  - dora
snooper_enabled: true
disable_peer_scoring: true
assertoor_params:
  image: "ethpandaops/assertoor:master"
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor-test/2a45f2f78dd2c336ac99bf15e61edc076f15ce67/assertoor-tests/block-proposal-check.yaml
```

Thanks for the fix :pray:
