### ISSUE TITLE
Fix minimal preset

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sifraitech/grandine#85]
@parithosh reported an issue with `minimal` preset:

> Gandine fails with a forkchoice assertion failure thread main panicked at /fork_choice_store/src/store.rs:227:9  assertion left == right failed (We used the image ethpandaops/grandine:develop-minimal

Kurtosis config to reproduce it:

```
participants:
  - el_type: geth
    cl_type: teku
  - el_type: geth
    cl_type: grandine
network_params:
  preset: minimal
  ```
  Kurtosis command:
  ` kurtosis run github.com/ethpandaops/ethereum-package --args-file ./minimal.yaml --enclave minimal --image-download always`
